// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: checkUpTime.sql

package db

import (
	"context"
	"database/sql"
)

const createCheckUpTime = `-- name: CreateCheckUpTime :execresult
INSERT INTO CheckUpTime (morning, evening, night)
VALUES (?, ?, ?)
`

type CreateCheckUpTimeParams struct {
	Morning sql.NullTime `json:"morning"`
	Evening sql.NullTime `json:"evening"`
	Night   sql.NullTime `json:"night"`
}

func (q *Queries) CreateCheckUpTime(ctx context.Context, arg CreateCheckUpTimeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCheckUpTime, arg.Morning, arg.Evening, arg.Night)
}

const deleteCheckUpTime = `-- name: DeleteCheckUpTime :exec
DELETE FROM CheckUpTime WHERE id = ?
`

func (q *Queries) DeleteCheckUpTime(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCheckUpTime, id)
	return err
}

const getCheckUpTime = `-- name: GetCheckUpTime :one
SELECT id, morning, evening, night FROM CheckUpTime WHERE id = ?
`

func (q *Queries) GetCheckUpTime(ctx context.Context, id int64) (Checkuptime, error) {
	row := q.db.QueryRowContext(ctx, getCheckUpTime, id)
	var i Checkuptime
	err := row.Scan(
		&i.ID,
		&i.Morning,
		&i.Evening,
		&i.Night,
	)
	return i, err
}

const listCheckUpTimes = `-- name: ListCheckUpTimes :many
SELECT id, morning, evening, night FROM CheckUpTime ORDER BY id LIMIT ? OFFSET ?
`

type ListCheckUpTimesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCheckUpTimes(ctx context.Context, arg ListCheckUpTimesParams) ([]Checkuptime, error) {
	rows, err := q.db.QueryContext(ctx, listCheckUpTimes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkuptime{}
	for rows.Next() {
		var i Checkuptime
		if err := rows.Scan(
			&i.ID,
			&i.Morning,
			&i.Evening,
			&i.Night,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckUpTime = `-- name: UpdateCheckUpTime :exec
UPDATE CheckUpTime SET morning = ?, evening = ?, night = ? WHERE id = ?
`

type UpdateCheckUpTimeParams struct {
	Morning sql.NullTime `json:"morning"`
	Evening sql.NullTime `json:"evening"`
	Night   sql.NullTime `json:"night"`
	ID      int64        `json:"id"`
}

func (q *Queries) UpdateCheckUpTime(ctx context.Context, arg UpdateCheckUpTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckUpTime,
		arg.Morning,
		arg.Evening,
		arg.Night,
		arg.ID,
	)
	return err
}
