// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: client.sql

package db

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :execresult
INSERT INTO Client (name, state, city, age)
VALUES (?, ?, ?, ?)
`

type CreateClientParams struct {
	Name  string `json:"name"`
	State string `json:"state"`
	City  string `json:"city"`
	Age   int32  `json:"age"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createClient,
		arg.Name,
		arg.State,
		arg.City,
		arg.Age,
	)
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM Client WHERE id = ?
`

func (q *Queries) DeleteClient(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, state, city, age FROM Client WHERE id = ?
`

func (q *Queries) GetClient(ctx context.Context, id int32) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.City,
		&i.Age,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, state, city, age FROM Client ORDER BY id LIMIT ? OFFSET ?
`

type ListClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.City,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :exec
UPDATE Client SET name = ?, state = ?, city = ?, age = ? WHERE id = ?
`

type UpdateClientParams struct {
	Name  string `json:"name"`
	State string `json:"state"`
	City  string `json:"city"`
	Age   int32  `json:"age"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) error {
	_, err := q.db.ExecContext(ctx, updateClient,
		arg.Name,
		arg.State,
		arg.City,
		arg.Age,
		arg.ID,
	)
	return err
}
