// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: doctor.sql

package db

import (
	"context"
	"database/sql"
)

const createDoctor = `-- name: CreateDoctor :execresult
INSERT INTO Doctor (
  Name, username, password, hospital_id, resident_address,
  isMorning, isEvening, isNight, checkup_time_id, isOnLeave
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDoctorParams struct {
	Name            string         `json:"name"`
	Username        string         `json:"username"`
	Password        string         `json:"password"`
	HospitalID      int32          `json:"hospital_id"`
	ResidentAddress sql.NullString `json:"resident_address"`
	Ismorning       sql.NullBool   `json:"ismorning"`
	Isevening       sql.NullBool   `json:"isevening"`
	Isnight         sql.NullBool   `json:"isnight"`
	CheckupTimeID   int32          `json:"checkup_time_id"`
	Isonleave       sql.NullBool   `json:"isonleave"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDoctor,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.HospitalID,
		arg.ResidentAddress,
		arg.Ismorning,
		arg.Isevening,
		arg.Isnight,
		arg.CheckupTimeID,
		arg.Isonleave,
	)
}

const deleteDoctor = `-- name: DeleteDoctor :exec
DELETE FROM Doctor WHERE id = ?
`

func (q *Queries) DeleteDoctor(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDoctor, id)
	return err
}

const getDoctor = `-- name: GetDoctor :one
SELECT id, name, username, password, hospital_id, resident_address, ismorning, isevening, isnight, checkup_time_id, isonleave FROM Doctor WHERE id = ?
`

func (q *Queries) GetDoctor(ctx context.Context, id int32) (Doctor, error) {
	row := q.db.QueryRowContext(ctx, getDoctor, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.HospitalID,
		&i.ResidentAddress,
		&i.Ismorning,
		&i.Isevening,
		&i.Isnight,
		&i.CheckupTimeID,
		&i.Isonleave,
	)
	return i, err
}

const listDoctors = `-- name: ListDoctors :many
SELECT id, name, username, password, hospital_id, resident_address, ismorning, isevening, isnight, checkup_time_id, isonleave FROM Doctor ORDER BY id
`

func (q *Queries) ListDoctors(ctx context.Context) ([]Doctor, error) {
	rows, err := q.db.QueryContext(ctx, listDoctors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Doctor{}
	for rows.Next() {
		var i Doctor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.HospitalID,
			&i.ResidentAddress,
			&i.Ismorning,
			&i.Isevening,
			&i.Isnight,
			&i.CheckupTimeID,
			&i.Isonleave,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoctor = `-- name: UpdateDoctor :exec
UPDATE Doctor SET
  Name = ?, username = ?, password = ?, hospital_id = ?, resident_address = ?,
  isMorning = ?, isEvening = ?, isNight = ?, checkup_time_id = ?, isOnLeave = ?
WHERE id = ?
`

type UpdateDoctorParams struct {
	Name            string         `json:"name"`
	Username        string         `json:"username"`
	Password        string         `json:"password"`
	HospitalID      int32          `json:"hospital_id"`
	ResidentAddress sql.NullString `json:"resident_address"`
	Ismorning       sql.NullBool   `json:"ismorning"`
	Isevening       sql.NullBool   `json:"isevening"`
	Isnight         sql.NullBool   `json:"isnight"`
	CheckupTimeID   int32          `json:"checkup_time_id"`
	Isonleave       sql.NullBool   `json:"isonleave"`
	ID              int32          `json:"id"`
}

func (q *Queries) UpdateDoctor(ctx context.Context, arg UpdateDoctorParams) error {
	_, err := q.db.ExecContext(ctx, updateDoctor,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.HospitalID,
		arg.ResidentAddress,
		arg.Ismorning,
		arg.Isevening,
		arg.Isnight,
		arg.CheckupTimeID,
		arg.Isonleave,
		arg.ID,
	)
	return err
}
