// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emergencyline.sql

package db

import (
	"context"
	"database/sql"
)

const countEmergencyLines = `-- name: CountEmergencyLines :one
SELECT COUNT(*) FROM EmergencyLine
`

func (q *Queries) CountEmergencyLines(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmergencyLines)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmergencyLine = `-- name: CreateEmergencyLine :execresult
INSERT INTO EmergencyLine (reg_time, token_number, client_id, doctor_id, isChecked, checked_time)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateEmergencyLineParams struct {
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int64        `json:"token_number"`
	ClientID    int64        `json:"client_id"`
	DoctorID    int64        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
}

func (q *Queries) CreateEmergencyLine(ctx context.Context, arg CreateEmergencyLineParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEmergencyLine,
		arg.RegTime,
		arg.TokenNumber,
		arg.ClientID,
		arg.DoctorID,
		arg.Ischecked,
		arg.CheckedTime,
	)
}

const deleteEmergencyLine = `-- name: DeleteEmergencyLine :exec
DELETE FROM EmergencyLine WHERE id = ?
`

func (q *Queries) DeleteEmergencyLine(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmergencyLine, id)
	return err
}

const getEmergencyLine = `-- name: GetEmergencyLine :one
SELECT id, reg_time, token_number, client_id, doctor_id, ischecked, checked_time FROM EmergencyLine WHERE id = ?
`

func (q *Queries) GetEmergencyLine(ctx context.Context, id int64) (Emergencyline, error) {
	row := q.db.QueryRowContext(ctx, getEmergencyLine, id)
	var i Emergencyline
	err := row.Scan(
		&i.ID,
		&i.RegTime,
		&i.TokenNumber,
		&i.ClientID,
		&i.DoctorID,
		&i.Ischecked,
		&i.CheckedTime,
	)
	return i, err
}

const listEmergencyLines = `-- name: ListEmergencyLines :many
SELECT id, reg_time, token_number, client_id, doctor_id, ischecked, checked_time FROM EmergencyLine ORDER BY reg_time DESC LIMIT ? OFFSET ?
`

type ListEmergencyLinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmergencyLines(ctx context.Context, arg ListEmergencyLinesParams) ([]Emergencyline, error) {
	rows, err := q.db.QueryContext(ctx, listEmergencyLines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Emergencyline{}
	for rows.Next() {
		var i Emergencyline
		if err := rows.Scan(
			&i.ID,
			&i.RegTime,
			&i.TokenNumber,
			&i.ClientID,
			&i.DoctorID,
			&i.Ischecked,
			&i.CheckedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmergencyWithDetails = `-- name: ListEmergencyWithDetails :many
SELECT 
  e.id, e.reg_time, e.token_number, e.isChecked, e.checked_time,
  c.name AS client_name,
  d.name AS doctor_name
FROM EmergencyLine e
JOIN Client c ON e.client_id = c.id
JOIN Doctor d ON e.doctor_id = d.id
ORDER BY e.reg_time DESC
LIMIT ? OFFSET ?
`

type ListEmergencyWithDetailsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListEmergencyWithDetailsRow struct {
	ID          int64        `json:"id"`
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int64        `json:"token_number"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
	ClientName  string       `json:"client_name"`
	DoctorName  string       `json:"doctor_name"`
}

func (q *Queries) ListEmergencyWithDetails(ctx context.Context, arg ListEmergencyWithDetailsParams) ([]ListEmergencyWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmergencyWithDetails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmergencyWithDetailsRow{}
	for rows.Next() {
		var i ListEmergencyWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegTime,
			&i.TokenNumber,
			&i.Ischecked,
			&i.CheckedTime,
			&i.ClientName,
			&i.DoctorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmergencyByDate = `-- name: SearchEmergencyByDate :many
SELECT 
  e.id, e.reg_time, e.token_number, e.isChecked, e.checked_time,
  c.name AS client_name,
  d.name AS doctor_name
FROM EmergencyLine e
JOIN Client c ON e.client_id = c.id
JOIN Doctor d ON e.doctor_id = d.id
WHERE e.reg_time BETWEEN ? AND ?
ORDER BY e.reg_time DESC
LIMIT ? OFFSET ?
`

type SearchEmergencyByDateParams struct {
	FromRegTime sql.NullTime `json:"from_reg_time"`
	ToRegTime   sql.NullTime `json:"to_reg_time"`
	Limit       int32        `json:"limit"`
	Offset      int32        `json:"offset"`
}

type SearchEmergencyByDateRow struct {
	ID          int64        `json:"id"`
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int64        `json:"token_number"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
	ClientName  string       `json:"client_name"`
	DoctorName  string       `json:"doctor_name"`
}

func (q *Queries) SearchEmergencyByDate(ctx context.Context, arg SearchEmergencyByDateParams) ([]SearchEmergencyByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, searchEmergencyByDate,
		arg.FromRegTime,
		arg.ToRegTime,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEmergencyByDateRow{}
	for rows.Next() {
		var i SearchEmergencyByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.RegTime,
			&i.TokenNumber,
			&i.Ischecked,
			&i.CheckedTime,
			&i.ClientName,
			&i.DoctorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmergencyLine = `-- name: UpdateEmergencyLine :exec
UPDATE EmergencyLine SET
  reg_time = ?, token_number = ?, client_id = ?, doctor_id = ?, isChecked = ?, checked_time = ?
WHERE id = ?
`

type UpdateEmergencyLineParams struct {
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int64        `json:"token_number"`
	ClientID    int64        `json:"client_id"`
	DoctorID    int64        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateEmergencyLine(ctx context.Context, arg UpdateEmergencyLineParams) error {
	_, err := q.db.ExecContext(ctx, updateEmergencyLine,
		arg.RegTime,
		arg.TokenNumber,
		arg.ClientID,
		arg.DoctorID,
		arg.Ischecked,
		arg.CheckedTime,
		arg.ID,
	)
	return err
}
