// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emergencyline.sql

package db

import (
	"context"
	"database/sql"
)

const createEmergencyLine = `-- name: CreateEmergencyLine :execresult
INSERT INTO EmergencyLine (reg_time, token_number, client_id, doctor_id, isChecked, checked_time)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateEmergencyLineParams struct {
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int32        `json:"token_number"`
	ClientID    int32        `json:"client_id"`
	DoctorID    int32        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
}

func (q *Queries) CreateEmergencyLine(ctx context.Context, arg CreateEmergencyLineParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEmergencyLine,
		arg.RegTime,
		arg.TokenNumber,
		arg.ClientID,
		arg.DoctorID,
		arg.Ischecked,
		arg.CheckedTime,
	)
}

const deleteEmergencyLine = `-- name: DeleteEmergencyLine :exec
DELETE FROM EmergencyLine WHERE id = ?
`

func (q *Queries) DeleteEmergencyLine(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEmergencyLine, id)
	return err
}

const getEmergencyLine = `-- name: GetEmergencyLine :one
SELECT id, reg_time, token_number, client_id, doctor_id, ischecked, checked_time FROM EmergencyLine WHERE id = ?
`

func (q *Queries) GetEmergencyLine(ctx context.Context, id int32) (Emergencyline, error) {
	row := q.db.QueryRowContext(ctx, getEmergencyLine, id)
	var i Emergencyline
	err := row.Scan(
		&i.ID,
		&i.RegTime,
		&i.TokenNumber,
		&i.ClientID,
		&i.DoctorID,
		&i.Ischecked,
		&i.CheckedTime,
	)
	return i, err
}

const listEmergencyLines = `-- name: ListEmergencyLines :many
SELECT id, reg_time, token_number, client_id, doctor_id, ischecked, checked_time FROM EmergencyLine ORDER BY reg_time DESC LIMIT ? OFFSET ?
`

type ListEmergencyLinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmergencyLines(ctx context.Context, arg ListEmergencyLinesParams) ([]Emergencyline, error) {
	rows, err := q.db.QueryContext(ctx, listEmergencyLines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Emergencyline{}
	for rows.Next() {
		var i Emergencyline
		if err := rows.Scan(
			&i.ID,
			&i.RegTime,
			&i.TokenNumber,
			&i.ClientID,
			&i.DoctorID,
			&i.Ischecked,
			&i.CheckedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmergencyLine = `-- name: UpdateEmergencyLine :exec
UPDATE EmergencyLine SET
  reg_time = ?, token_number = ?, client_id = ?, doctor_id = ?, isChecked = ?, checked_time = ?
WHERE id = ?
`

type UpdateEmergencyLineParams struct {
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int32        `json:"token_number"`
	ClientID    int32        `json:"client_id"`
	DoctorID    int32        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
	ID          int32        `json:"id"`
}

func (q *Queries) UpdateEmergencyLine(ctx context.Context, arg UpdateEmergencyLineParams) error {
	_, err := q.db.ExecContext(ctx, updateEmergencyLine,
		arg.RegTime,
		arg.TokenNumber,
		arg.ClientID,
		arg.DoctorID,
		arg.Ischecked,
		arg.CheckedTime,
		arg.ID,
	)
	return err
}
