// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hospital.sql

package db

import (
	"context"
	"database/sql"
)

const countHospitals = `-- name: CountHospitals :one
SELECT COUNT(*) FROM Hospital
`

func (q *Queries) CountHospitals(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHospitals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHospital = `-- name: CreateHospital :execresult
INSERT INTO Hospital (name, photo, state, city, address, phone)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateHospitalParams struct {
	Name    string         `json:"name"`
	Photo   sql.NullString `json:"photo"`
	State   string         `json:"state"`
	City    string         `json:"city"`
	Address string         `json:"address"`
	Phone   sql.NullString `json:"phone"`
}

func (q *Queries) CreateHospital(ctx context.Context, arg CreateHospitalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHospital,
		arg.Name,
		arg.Photo,
		arg.State,
		arg.City,
		arg.Address,
		arg.Phone,
	)
}

const deleteHospital = `-- name: DeleteHospital :exec
DELETE FROM Hospital WHERE id = ?
`

func (q *Queries) DeleteHospital(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHospital, id)
	return err
}

const getHospital = `-- name: GetHospital :one
SELECT id, name, photo, state, city, address, phone FROM Hospital WHERE id = ?
`

func (q *Queries) GetHospital(ctx context.Context, id int64) (Hospital, error) {
	row := q.db.QueryRowContext(ctx, getHospital, id)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Photo,
		&i.State,
		&i.City,
		&i.Address,
		&i.Phone,
	)
	return i, err
}

const listHospitals = `-- name: ListHospitals :many
SELECT id, name, photo, state, city, address, phone FROM Hospital ORDER BY id LIMIT ? OFFSET ?
`

type ListHospitalsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListHospitals(ctx context.Context, arg ListHospitalsParams) ([]Hospital, error) {
	rows, err := q.db.QueryContext(ctx, listHospitals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hospital{}
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Photo,
			&i.State,
			&i.City,
			&i.Address,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHospitalsByLocation = `-- name: ListHospitalsByLocation :many
SELECT id, name, photo, state, city, address, phone FROM Hospital
WHERE state = ? AND city = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListHospitalsByLocationParams struct {
	State  string `json:"state"`
	City   string `json:"city"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListHospitalsByLocation(ctx context.Context, arg ListHospitalsByLocationParams) ([]Hospital, error) {
	rows, err := q.db.QueryContext(ctx, listHospitalsByLocation,
		arg.State,
		arg.City,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hospital{}
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Photo,
			&i.State,
			&i.City,
			&i.Address,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHospitalsByName = `-- name: SearchHospitalsByName :many
SELECT id, name, photo, state, city, address, phone FROM Hospital
WHERE name LIKE ?
ORDER BY id
LIMIT ? OFFSET ?
`

type SearchHospitalsByNameParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchHospitalsByName(ctx context.Context, arg SearchHospitalsByNameParams) ([]Hospital, error) {
	rows, err := q.db.QueryContext(ctx, searchHospitalsByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hospital{}
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Photo,
			&i.State,
			&i.City,
			&i.Address,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHospital = `-- name: UpdateHospital :exec
UPDATE Hospital
SET name = ?, photo = ?, state = ?, city = ?, address = ?, phone = ?
WHERE id = ?
`

type UpdateHospitalParams struct {
	Name    string         `json:"name"`
	Photo   sql.NullString `json:"photo"`
	State   string         `json:"state"`
	City    string         `json:"city"`
	Address string         `json:"address"`
	Phone   sql.NullString `json:"phone"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateHospital(ctx context.Context, arg UpdateHospitalParams) error {
	_, err := q.db.ExecContext(ctx, updateHospital,
		arg.Name,
		arg.Photo,
		arg.State,
		arg.City,
		arg.Address,
		arg.Phone,
		arg.ID,
	)
	return err
}
