// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type UserGender string

const (
	UserGenderMALE   UserGender = "MALE"
	UserGenderFEMALE UserGender = "FEMALE"
	UserGenderOTHER  UserGender = "OTHER"
)

func (e *UserGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserGender(s)
	case string:
		*e = UserGender(s)
	default:
		return fmt.Errorf("unsupported scan type for UserGender: %T", src)
	}
	return nil
}

type NullUserGender struct {
	UserGender UserGender `json:"user_gender"`
	Valid      bool       `json:"valid"` // Valid is true if UserGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserGender) Scan(value interface{}) error {
	if value == nil {
		ns.UserGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserGender), nil
}

type Checkuptime struct {
	ID      int64        `json:"id"`
	Morning sql.NullTime `json:"morning"`
	Evening sql.NullTime `json:"evening"`
	Night   sql.NullTime `json:"night"`
}

type Client struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	State  string `json:"state"`
	City   string `json:"city"`
	Number int64  `json:"number"`
	Age    int32  `json:"age"`
}

type Doctor struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	Username        string         `json:"username"`
	Password        string         `json:"password"`
	HospitalID      int64          `json:"hospital_id"`
	ResidentAddress sql.NullString `json:"resident_address"`
	CheckupTimeID   int64          `json:"checkup_time_id"`
	IsOnLeave       sql.NullBool   `json:"is_on_leave"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Doctorspeciality struct {
	ID           int64 `json:"id"`
	SpecialityID int64 `json:"speciality_id"`
	DocterID     int64 `json:"docter_id"`
}

type Emergencyline struct {
	ID          int64        `json:"id"`
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int64        `json:"token_number"`
	ClientID    int64        `json:"client_id"`
	DoctorID    int64        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
}

type Hospital struct {
	ID      int64          `json:"id"`
	Name    string         `json:"name"`
	Photo   sql.NullString `json:"photo"`
	State   string         `json:"state"`
	City    string         `json:"city"`
	Address string         `json:"address"`
	Phone   sql.NullString `json:"phone"`
}

type Opdline struct {
	ID          int64        `json:"id"`
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int32        `json:"token_number"`
	ClientID    int64        `json:"client_id"`
	DoctorID    int64        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
}

type Speciality struct {
	ID             int64  `json:"id"`
	SpecialityName string `json:"speciality_name"`
}

type User struct {
	ID       int64         `json:"id"`
	Name     string        `json:"name"`
	Password string        `json:"password"`
	State    string        `json:"state"`
	City     string        `json:"city"`
	Gender   UserGender    `json:"gender"`
	Age      sql.NullInt32 `json:"age"`
}
