// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: opdline.sql

package db

import (
	"context"
	"database/sql"
)

const createOPDLine = `-- name: CreateOPDLine :execresult
INSERT INTO OPDLine (reg_time, token_number, client_id, doctor_id, isChecked, checked_time)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOPDLineParams struct {
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int32        `json:"token_number"`
	ClientID    int32        `json:"client_id"`
	DoctorID    int32        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
}

func (q *Queries) CreateOPDLine(ctx context.Context, arg CreateOPDLineParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOPDLine,
		arg.RegTime,
		arg.TokenNumber,
		arg.ClientID,
		arg.DoctorID,
		arg.Ischecked,
		arg.CheckedTime,
	)
}

const deleteOPDLine = `-- name: DeleteOPDLine :exec
DELETE FROM OPDLine WHERE id = ?
`

func (q *Queries) DeleteOPDLine(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteOPDLine, id)
	return err
}

const getOPDLine = `-- name: GetOPDLine :one
SELECT id, reg_time, token_number, client_id, doctor_id, ischecked, checked_time FROM OPDLine WHERE id = ?
`

func (q *Queries) GetOPDLine(ctx context.Context, id int32) (Opdline, error) {
	row := q.db.QueryRowContext(ctx, getOPDLine, id)
	var i Opdline
	err := row.Scan(
		&i.ID,
		&i.RegTime,
		&i.TokenNumber,
		&i.ClientID,
		&i.DoctorID,
		&i.Ischecked,
		&i.CheckedTime,
	)
	return i, err
}

const listOPDLines = `-- name: ListOPDLines :many
SELECT id, reg_time, token_number, client_id, doctor_id, ischecked, checked_time FROM OPDLine ORDER BY reg_time DESC LIMIT ? OFFSET ?
`

type ListOPDLinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOPDLines(ctx context.Context, arg ListOPDLinesParams) ([]Opdline, error) {
	rows, err := q.db.QueryContext(ctx, listOPDLines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Opdline{}
	for rows.Next() {
		var i Opdline
		if err := rows.Scan(
			&i.ID,
			&i.RegTime,
			&i.TokenNumber,
			&i.ClientID,
			&i.DoctorID,
			&i.Ischecked,
			&i.CheckedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOPDLine = `-- name: UpdateOPDLine :exec
UPDATE OPDLine SET
  reg_time = ?, token_number = ?, client_id = ?, doctor_id = ?, isChecked = ?, checked_time = ?
WHERE id = ?
`

type UpdateOPDLineParams struct {
	RegTime     sql.NullTime `json:"reg_time"`
	TokenNumber int32        `json:"token_number"`
	ClientID    int32        `json:"client_id"`
	DoctorID    int32        `json:"doctor_id"`
	Ischecked   bool         `json:"ischecked"`
	CheckedTime sql.NullTime `json:"checked_time"`
	ID          int32        `json:"id"`
}

func (q *Queries) UpdateOPDLine(ctx context.Context, arg UpdateOPDLineParams) error {
	_, err := q.db.ExecContext(ctx, updateOPDLine,
		arg.RegTime,
		arg.TokenNumber,
		arg.ClientID,
		arg.DoctorID,
		arg.Ischecked,
		arg.CheckedTime,
		arg.ID,
	)
	return err
}
