// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: speciality.sql

package db

import (
	"context"
	"database/sql"
)

const countSpecialities = `-- name: CountSpecialities :one
SELECT COUNT(*) FROM Speciality
`

func (q *Queries) CountSpecialities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpecialities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpeciality = `-- name: CreateSpeciality :execresult
INSERT INTO Speciality (speciality_name)
VALUES (?)
`

func (q *Queries) CreateSpeciality(ctx context.Context, specialityName string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSpeciality, specialityName)
}

const deleteSpeciality = `-- name: DeleteSpeciality :exec
DELETE FROM Speciality WHERE id = ?
`

func (q *Queries) DeleteSpeciality(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpeciality, id)
	return err
}

const getSpeciality = `-- name: GetSpeciality :one
SELECT id, speciality_name FROM Speciality WHERE id = ?
`

func (q *Queries) GetSpeciality(ctx context.Context, id int64) (Speciality, error) {
	row := q.db.QueryRowContext(ctx, getSpeciality, id)
	var i Speciality
	err := row.Scan(&i.ID, &i.SpecialityName)
	return i, err
}

const listSpecialities = `-- name: ListSpecialities :many
SELECT id, speciality_name FROM Speciality ORDER BY id LIMIT ? OFFSET ?
`

type ListSpecialitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSpecialities(ctx context.Context, arg ListSpecialitiesParams) ([]Speciality, error) {
	rows, err := q.db.QueryContext(ctx, listSpecialities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Speciality{}
	for rows.Next() {
		var i Speciality
		if err := rows.Scan(&i.ID, &i.SpecialityName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpecialitiesByName = `-- name: SearchSpecialitiesByName :many
SELECT id, speciality_name FROM Speciality
WHERE speciality_name LIKE ?
ORDER BY speciality_name
LIMIT ? OFFSET ?
`

type SearchSpecialitiesByNameParams struct {
	SpecialityName string `json:"speciality_name"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchSpecialitiesByName(ctx context.Context, arg SearchSpecialitiesByNameParams) ([]Speciality, error) {
	rows, err := q.db.QueryContext(ctx, searchSpecialitiesByName, arg.SpecialityName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Speciality{}
	for rows.Next() {
		var i Speciality
		if err := rows.Scan(&i.ID, &i.SpecialityName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpeciality = `-- name: UpdateSpeciality :exec
UPDATE Speciality SET speciality_name = ? WHERE id = ?
`

type UpdateSpecialityParams struct {
	SpecialityName string `json:"speciality_name"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateSpeciality(ctx context.Context, arg UpdateSpecialityParams) error {
	_, err := q.db.ExecContext(ctx, updateSpeciality, arg.SpecialityName, arg.ID)
	return err
}
