// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM User
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO User (username, full_name, hashed_password, state, city, gender, password_changed_at, age)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Username          string        `json:"username"`
	FullName          string        `json:"full_name"`
	HashedPassword    string        `json:"hashed_password"`
	State             string        `json:"state"`
	City              string        `json:"city"`
	Gender            UserGender    `json:"gender"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	Age               sql.NullInt32 `json:"age"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.HashedPassword,
		arg.State,
		arg.City,
		arg.Gender,
		arg.PasswordChangedAt,
		arg.Age,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM User WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, full_name, hashed_password, state, city, gender, password_changed_at, age FROM User WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.HashedPassword,
		&i.State,
		&i.City,
		&i.Gender,
		&i.PasswordChangedAt,
		&i.Age,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, full_name, hashed_password, state, city, gender, password_changed_at, age FROM User ORDER BY id LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.HashedPassword,
			&i.State,
			&i.City,
			&i.Gender,
			&i.PasswordChangedAt,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByGenderAndCity = `-- name: ListUsersByGenderAndCity :many
SELECT id, username, full_name, hashed_password, state, city, gender, password_changed_at, age FROM User
WHERE gender = ? AND city = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListUsersByGenderAndCityParams struct {
	Gender UserGender `json:"gender"`
	City   string     `json:"city"`
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
}

func (q *Queries) ListUsersByGenderAndCity(ctx context.Context, arg ListUsersByGenderAndCityParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByGenderAndCity,
		arg.Gender,
		arg.City,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.HashedPassword,
			&i.State,
			&i.City,
			&i.Gender,
			&i.PasswordChangedAt,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT id, username, full_name, hashed_password, state, city, gender, password_changed_at, age FROM User
WHERE full_name LIKE ?
ORDER BY id
LIMIT ? OFFSET ?
`

type SearchUsersByNameParams struct {
	FullName string `json:"full_name"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByName, arg.FullName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.HashedPassword,
			&i.State,
			&i.City,
			&i.Gender,
			&i.PasswordChangedAt,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE User SET username = ?, full_name = ?, hashed_password = ?, state = ?, city = ?, gender = ?, password_changed_at = ?, age = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username          string        `json:"username"`
	FullName          string        `json:"full_name"`
	HashedPassword    string        `json:"hashed_password"`
	State             string        `json:"state"`
	City              string        `json:"city"`
	Gender            UserGender    `json:"gender"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	Age               sql.NullInt32 `json:"age"`
	ID                int64         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.FullName,
		arg.HashedPassword,
		arg.State,
		arg.City,
		arg.Gender,
		arg.PasswordChangedAt,
		arg.Age,
		arg.ID,
	)
	return err
}
