// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO User (name, password, state, city, gender, age)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Name     string        `json:"name"`
	Password string        `json:"password"`
	State    string        `json:"state"`
	City     string        `json:"city"`
	Gender   UserGender    `json:"gender"`
	Age      sql.NullInt32 `json:"age"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Password,
		arg.State,
		arg.City,
		arg.Gender,
		arg.Age,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM User WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, password, state, city, gender, age FROM User WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.State,
		&i.City,
		&i.Gender,
		&i.Age,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, password, state, city, gender, age FROM User ORDER BY id LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Password,
			&i.State,
			&i.City,
			&i.Gender,
			&i.Age,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE User SET name = ?, password = ?, state = ?, city = ?, gender = ?, age = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name     string        `json:"name"`
	Password string        `json:"password"`
	State    string        `json:"state"`
	City     string        `json:"city"`
	Gender   UserGender    `json:"gender"`
	Age      sql.NullInt32 `json:"age"`
	ID       int32         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Password,
		arg.State,
		arg.City,
		arg.Gender,
		arg.Age,
		arg.ID,
	)
	return err
}
